### ISSUE TITLE
can not crop

### ISSUE THREAD

**Issue by wblbird** [noam148/yii2-image-manager#32]
all config follow on README.md 
it works well ,can upload image ,can delete image 
when I corp a image ，it alert “Error: item is not  cropped”

**Comment by noam148** [comment]
Can you show me your ajax request response? When the crop apply the code send a ajax request with the position and sizes. With that data php cropped the image. But its possible that php hasn't got enough memory and than the code crashed.

If it crashe php return error in the ajax request. Can you show me the response?

**Comment by wblbird** [comment]
5968e9a84db70: POST http://127.0.0.1/index.php?r=imagemanager%2Fmanager/crop at 2017-07-14 03:56:24 pm by 127.0.0.1

CropData
[
    'x' => '75.5086956521739'
    'y' => '33.93260869565217'
    'width' => '456'
    'height' => '378.3999999999999'
    'rotate' => '0'
    'scaleX' => '1'
    'scaleY' => '1'
]

**Comment by noam148** [comment]
Thanks for the post data, but can you give me also the response data?

**Comment by wblbird** [comment]
596a19468b51d: POST http://127.0.0.1/index.php?r=imagemanager%2Fmanager/crop at 2017-07-15 01:31:50 pm by 127.0.0.1

Response Headers
<table class="table table-condensed table-bordered table-striped table-hover request-table" style="table-layout: fixed;">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                            <tr>
                    <th>X-Powered-By</th>
                    <td>'PHP/7.0.12'</td>
                </tr>
                            <tr>
                    <th>Content-Type</th>
                    <td>'application/json; charset=UTF-8'</td>
                </tr>
                            <tr>
                    <th>X-Debug-Tag</th>
                    <td>'596a19468b51d'</td>
                </tr>
                            <tr>
                    <th>X-Debug-Duration</th>
                    <td>'136'</td>
                </tr>
                            <tr>
                    <th>X-Debug-Link</th>
                    <td>'/index.php?r=debug%2Fdefault%2Fview&amp;tag=596a19468b51d'</td>
                </tr>
                        </tbody>
        </table>

**Comment by wblbird** [comment]
596a19406d72e: POST http://127.0.0.1/index.php?r=imagemanager%2Fmanager/get-original-image at 2017-07-15 01:31:44 pm by 127.0.0.1

Response Headers
<table class="table table-condensed table-bordered table-striped table-hover request-table" style="table-layout: fixed;">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                            <tr>
                    <th>X-Powered-By</th>
                    <td>'PHP/7.0.12'</td>
                </tr>
                            <tr>
                    <th>Content-Type</th>
                    <td>'application/json; charset=UTF-8'</td>
                </tr>
                            <tr>
                    <th>X-Debug-Tag</th>
                    <td>'596a19406d72e'</td>
                </tr>
                            <tr>
                    <th>X-Debug-Duration</th>
                    <td>'159'</td>
                </tr>
                            <tr>
                    <th>X-Debug-Link</th>
                    <td>'/index.php?r=debug%2Fdefault%2Fview&amp;tag=596a19406d72e'</td>
                </tr>
                        </tbody>
        </table>

**Comment by wblbird** [comment]
596a193d56365: POST http://127.0.0.1/index.php?r=imagemanager%2Fmanager/view at 2017-07-15 01:31:41 pm by 127.0.0.1

<table class="table table-condensed table-bordered table-striped table-hover request-table" style="table-layout: fixed;">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                            <tr>
                    <th>Content Type</th>
                    <td>'application/x-www-form-urlencoded; charset=UTF-8'</td>
                </tr>
                            <tr>
                    <th>Raw</th>
                    <td>'ImageManager_id=10&amp;_csrf=70K70ZUQonWVuptthuLHECj6vc3KqYDMiyACrEWsPF90BEk4NP1FvwZc5DalBnj0CKp3cuqVHj_L2EfH58CZ_g%3D%3D'</td>
                </tr>
                            <tr>
                    <th>Decoded to Params</th>
                    <td>[
    'ImageManager_id' =&gt; '10'
    '_csrf' =&gt; '70K70ZUQonWVuptthuLHECj6vc3KqYDMiyACrEWsPF90BEk4NP1FvwZc5DalBnj0CKp3cuqVHj_L2EfH58CZ_g=='
]</td>
                </tr>
                        </tbody>
        </table>

**Comment by noam148** [comment]
Sorry if im not clear, but I need the response of the crop request. See below:
![response](https://user-images.githubusercontent.com/10885039/28337883-55fa4432-6c07-11e7-9614-b4269686796b.png)

**Comment by wblbird** [comment]
{"name":"Exception","message":"Class 'Imagine\\Image\\Palette\\RGB' not found","code":0,"type":"Error"
,"file":"D:\\qampp_app\\htdocs\\vendor\\noam148\\yii2-image-manager\\controllers\\ManagerController.php"
,"line":296,"stack-trace":["#0 [internal function]: noam148\\imagemanager\\controllers\\ManagerController-
>actionCrop()","#1 D:\\qampp_app\\htdocs\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(57): call_user_func_array
(Array, Array)","#2 D:\\qampp_app\\htdocs\\vendor\\yiisoft\\yii2\\base\\Controller.php(156): yii\\base
\\InlineAction->runWithParams(Array)","#3 D:\\qampp_app\\htdocs\\vendor\\yiisoft\\yii2\\base\\Module
.php(523): yii\\base\\Controller->runAction('crop', Array)","#4 D:\\qampp_app\\htdocs\\vendor\\yiisoft
\\yii2\\web\\Application.php(102): yii\\base\\Module->runAction('imagemanager/ma...', Array)","#5 D:
\\qampp_app\\htdocs\\vendor\\yiisoft\\yii2\\base\\Application.php(380): yii\\web\\Application->handleRequest
(Object(yii\\web\\Request))","#6 D:\\qampp_app\\htdocs\\web\\index.php(12): yii\\base\\Application->run
()","#7 {main}"]}

**Comment by wblbird** [comment]
POST http://127.0.0.1/index.php?r=imagemanager%2Fmanager/crop | 500 Internal Server Error |   | 189ms

**Comment by noam148** [comment]
Thats what i need! Do you use a specific version of Imagine in your composer file? I looks like Imagine\Image\Palette\RGB not exists in the version that you used.

**Comment by wblbird** [comment]
Thank you for your reply。let me check it，and  version of Imagine is 0.5.0

**Comment by noam148** [comment]
Try to update it to 0.6.3

That the version I used.

**Comment by maz0717** [comment]
I'm getting the same crash.  With the same error.    I think a dependency in the image manager composer file should be added.
